name: Continuous Integration
on:
  workflow_dispatch:
    inputs:
      go-fdo-server-branch:
        description: Go FDO server branch
        default: main
        required: true
  push:
    branches:
      - main
  pull_request:
jobs:
  test-makefile:
    name: build and test makefile
    runs-on: ubuntu-latest
    steps:
      - name: Install golang
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version: "1.25"

      - name: Check out repository code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Build and install the binary
        run: |
           make && sudo install -D -m 755 go-fdo-client /usr/bin/

      - name: Fail if the source code has changes after build
        uses: NathanielHill/fail-if-changes@043d2f3e52828fd3e37eb59acd44ef9d2e2b82bc # master

      - name: Generate certs
        run: |
          source .github/scripts/fdo-utils.sh
          generate_certs

      - name: Build and spawn FDO server containers
        id: build-and-run-servers
        uses: hoverkraft-tech/compose-action@40041ff1b97dbf152cd2361138c2b03fa29139df # v2.3.0
        with:
          compose-file: ".github/compose/servers.yaml"
          services-log-level: debug
          up-flags: "--build"
        env:
          GO_FDO_SERVER_FLAGS: ${{inputs.go-fdo-server-branch}}

      - name: Test FIDO Device Onboarding
        run: |
          source .github/scripts/fdo-utils.sh
          test_onboarding

      - name: Get Manufacturer, Rendezvous and Owner server logs
        run: |
          source .github/scripts/fdo-utils.sh
          get_server_logs

  test-container:
    name: build and test containers
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Build the client container
        run: |
          docker build -t go-fdo-client .

      - name: Fail if the source code has changes after build
        uses: NathanielHill/fail-if-changes@043d2f3e52828fd3e37eb59acd44ef9d2e2b82bc # master

      - name: Generate certs
        run: |
          source .github/scripts/fdo-utils.sh
          generate_certs

      - name: Build and spawn FDO server containers
        id: build-and-run-servers
        uses: hoverkraft-tech/compose-action@40041ff1b97dbf152cd2361138c2b03fa29139df # v2.3.0
        with:
          compose-file: ".github/compose/servers.yaml"
          services-log-level: debug
          up-flags: "--build"
        env:
          GO_FDO_SERVER_FLAGS: ${{inputs.go-fdo-server-branch}}

      - name: Test FIDO Device Onboarding
        run: |
          source .github/scripts/container-utils.sh
          test_onboarding

      - name: Get Manufacturer, Rendezvous and Owner server logs
        run: |
          source .github/scripts/container-utils.sh
          get_server_logs
